FROM node:23-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY prisma ./prisma
COPY .env ./
RUN npm install
COPY . .
RUN npx prisma generate
RUN npx prisma migrate deploy
EXPOSE 3001
CMD ["npm", "run", "server"]