FROM node:23.1.0-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Скомпилируй TypeScript
RUN npm run build:server

# Убедись, что Prisma сгенерировала клиент
RUN npx prisma generate

EXPOSE 3000

CMD ["node", "dist/server/index.js"]