import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Водка Xaoma Original Tien Shan 0.5 л',
    image: '/images/xaoma-tien-shan.jpg',
    price: 169,
    oldPrice: 209,
    inStock: true,
    article: '16189',
    isClub: true,
    isPromo: true,
    discountPercent: 19,
    economy: 40,
    availableText: 'Есть в наличии',
  },
  {
    id: '2',
    name: 'Виски Highland Baron Blended Scotch 0.7 л',
    image: '/images/highland-baron.jpg',
    price: 329,
    oldPrice: 399,
    inStock: true,
    article: '16140',
    isClub: true,
    isPromo: true,
    discountPercent: 18,
    economy: 70,
    availableText: 'Есть в наличии',
  },
  {
    id: '3',
    name: 'Пиво Will-Brau Hefeweizen светлое нефильтр. 0.5 л',
    image: '/images/will-brau.jpg',
    price: 69,
    oldPrice: 89,
    inStock: true,
    article: '15984',
    isClub: true,
    isPromo: true,
    discountPercent: 22,
    economy: 20,
    availableText: 'Есть в наличии',
  },
  {
    id: '4',
    name: 'Ром Bardett Spiced 0.7 л',
    image: '/images/bardett-spiced.jpg',
    price: 299,
    oldPrice: 395,
    inStock: true,
    article: '15597',
    isClub: true,
    isPromo: true,
    discountPercent: 24,
    economy: 96,
    availableText: 'Есть в наличии',
  },
  {
    id: '5',
    name: 'Пиво Oettinger Bavarian Helles светлое пастер. ж/б 0.5 л',
    image: '/images/oettinger.jpg',
    price: 34,
    oldPrice: 46,
    inStock: true,
    article: '14879',
    isClub: true,
    isPromo: true,
    discountPercent: 26,
    economy: 12,
    availableText: 'Есть в наличии',
  },
]; 